# Generated by Django 5.1.1 on 2024-09-17 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'verbose_name': 'Семестр', 'verbose_name_plural': 'Семестры'},
        ),
        migrations.AlterModelTable(
            name='course',
            table='Course',
        ),
        migrations.AlterModelTable(
            name='semester',
            table='Semester',
        ),
    ]
