# Generated by Django 5.1.1 on 2024-09-08 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='form_of_study',
            new_name='form',
        ),
        migrations.AlterField(
            model_name='student',
            name='health',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.health', verbose_name='Группа здоровья'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.profile', verbose_name='Профиль обучения'),
        ),
    ]
