# Generated by Django 5.1.1 on 2024-09-09 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_form_of_study_profile_form_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Статус элективного курса')),
            ],
        ),
        migrations.CreateModel(
            name='Elective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('describe', models.TextField(null=True, verbose_name='Описание')),
                ('place', models.IntegerField(null=True, verbose_name='Количество мест')),
                ('volume', models.IntegerField(null=True, verbose_name='Объем')),
                ('date_registration', models.DateField(null=True)),
                ('date_start', models.DateField(null=True)),
                ('date_finish', models.DateField(null=True)),
                ('marks', models.FloatField(null=True, verbose_name='Минимальный балл')),
                ('registration_closed', models.BooleanField(default=False, verbose_name='Регистрация закрыта')),
                ('form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.form')),
                ('health', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.health')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.status')),
            ],
            options={
                'verbose_name': 'Электив',
                'verbose_name_plural': 'Элективы',
                'db_table': 'Elective',
            },
        ),
        migrations.CreateModel(
            name='TeacherElective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elective', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.elective', verbose_name='Элективный курс')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.teacher', verbose_name='Преподаватель')),
            ],
        ),
    ]
