# Generated by Django 5.1.1 on 2024-09-17 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_course_options_alter_semester_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='value',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='semester',
            old_name='value',
            new_name='name',
        ),
    ]
