# Generated by Django 5.1.1 on 2024-09-19 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_value_course_name_rename_value_semester_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electiveprofile',
            name='assign_all_semestrs',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='electiveprofile',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.course'),
        ),
        migrations.AlterField(
            model_name='electiveprofile',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.semester'),
        ),
    ]
