# Generated by Django 5.1.1 on 2024-09-09 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_status_elective_teacherelective'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='status',
            table='Status',
        ),
    ]
