# Generated by Django 5.1.1 on 2024-09-19 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_electiveprofile_assign_all_semestrs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultet',
            name='institute',
        ),
        migrations.CreateModel(
            name='Ugsn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='УГСН')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.institute', verbose_name='Институт')),
            ],
        ),
        migrations.AddField(
            model_name='facultet',
            name='ugsn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ugsn', verbose_name='УГСН'),
        ),
    ]
