# Generated by Django 5.1.1 on 2024-09-09 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_status_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teacherelective',
            table='TeacherElective',
        ),
    ]
