# Generated by Django 5.1.1 on 2024-09-19 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_facultet_institute_ugsn_facultet_ugsn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ugsn',
            options={'verbose_name': 'УГСН', 'verbose_name_plural': 'УГСН'},
        ),
        migrations.AlterModelTable(
            name='ugsn',
            table='Ugsn',
        ),
    ]
