# Generated by Django 5.1.1 on 2024-09-09 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_teacherelective_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherelective',
            options={'verbose_name': 'Преподаватель в элективе', 'verbose_name_plural': 'Преподаватели в элективе'},
        ),
        migrations.AlterField(
            model_name='elective',
            name='date_registration',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
