# Generated by Django 5.1.1 on 2024-09-10 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_teacherelective_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentElective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elective', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.elective', verbose_name='Электив')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Студент в элективе',
                'verbose_name_plural': 'Студенты в элективе',
                'db_table': 'StudentElective',
            },
        ),
    ]
