# Generated by Django 5.1.1 on 2024-09-19 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_type_admin_elective_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': 'Тип курса', 'verbose_name_plural': 'Тип курсов'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Тип курса', 'verbose_name_plural': 'Тип курсов'},
        ),
        migrations.AlterModelTable(
            name='admin',
            table='Admin',
        ),
        migrations.AlterModelTable(
            name='type',
            table='Type',
        ),
    ]
