# Generated by Django 5.1.1 on 2024-09-12 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_studentelective'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectiveFacultet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestr', models.PositiveIntegerField(blank=True, null=True)),
                ('assign_all_courses', models.BooleanField(default=False)),
                ('elective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.elective')),
                ('facultet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.facultet')),
            ],
            options={
                'verbose_name': 'Направления подготовки в элективе',
                'verbose_name_plural': 'Направления подготовки в элективе',
                'db_table': 'ElectiveFacultet',
            },
        ),
        migrations.CreateModel(
            name='ElectiveInstitute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestr', models.PositiveIntegerField(blank=True, null=True)),
                ('assign_all_courses', models.BooleanField(default=False)),
                ('elective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.elective')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.institute')),
            ],
            options={
                'verbose_name': 'Институт в элективе',
                'verbose_name_plural': 'Институты в элективе',
                'db_table': 'ElectiveInstitute',
            },
        ),
        migrations.CreateModel(
            name='ElectiveProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestr', models.PositiveIntegerField(blank=True, null=True)),
                ('assign_all_courses', models.BooleanField(default=False)),
                ('elective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.elective')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
            ],
            options={
                'verbose_name': 'Профили подготовки в элективе',
                'verbose_name_plural': 'Профили подготовки в элективе',
                'db_table': 'ElectiveProfile',
            },
        ),
    ]
