# Generated by Django 5.1.1 on 2024-09-20 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_admin_options_alter_type_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electiveprofile',
            name='assign_all_semestrs',
        ),
        migrations.RemoveField(
            model_name='electiveprofile',
            name='course',
        ),
        migrations.RemoveField(
            model_name='electiveprofile',
            name='semester',
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.semester'),
        ),
        migrations.CreateModel(
            name='ElectiveProfileCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_course', models.BooleanField(default=False, verbose_name='Назначен ли всем курсам')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('electiveprofile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.electiveprofile')),
            ],
            options={
                'verbose_name_plural': 'Курсы в профиле в элективе',
                'db_table': 'ElectiveProfileCourse',
            },
        ),
    ]
