# Generated by Django 5.1.1 on 2024-09-12 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_assign_all_courses_electivefacultet_assign_all_semestrs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elective',
            name='made_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.teacher'),
        ),
    ]
