# Generated by Django 5.1.1 on 2024-09-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_elective_made_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='electivefacultet',
            name='course',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electiveinstitute',
            name='course',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electiveprofile',
            name='course',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
