# Generated by Django 5.1.1 on 2024-09-20 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_coursesemester_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус элективного курса', 'verbose_name_plural': 'Статусы элективного курса'},
        ),
        migrations.AddField(
            model_name='semester',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.course'),
        ),
        migrations.DeleteModel(
            name='CourseSemester',
        ),
    ]
