# Generated by Django 5.1.1 on 2024-09-22 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_status_options_semester_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electiveprofile',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.semester'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.course', verbose_name='Курс'),
        ),
    ]
