# Generated by Django 5.1.1 on 2024-09-22 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_electiveprofile_semester_alter_semester_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electiveprofile',
            name='semester',
        ),
    ]
