# Generated by Django 5.1.1 on 2024-09-22 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_electiveprofile_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electiveprofilecourse',
            name='course',
        ),
        migrations.AddField(
            model_name='electiveprofilecourse',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.semester'),
        ),
    ]
