# Generated by Django 5.1.1 on 2024-09-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_electiveprofilecourse_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elective',
            name='note',
            field=models.TextField(null=True, verbose_name='Примечание преподавателя'),
        ),
    ]
