# Generated by Django 5.1.1 on 2024-09-28 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_elective_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusByAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
            ],
        ),
        migrations.AddField(
            model_name='elective',
            name='admin_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.statusbyadmin'),
        ),
    ]
