# Generated by Django 5.1.1 on 2024-09-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_statusbyadmin_elective_admin_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': 'Админ', 'verbose_name_plural': 'Администрация'},
        ),
        migrations.AlterModelOptions(
            name='statusbyadmin',
            options={'verbose_name': 'Статус проверки', 'verbose_name_plural': 'Статусы проверки'},
        ),
        migrations.AddField(
            model_name='statusbyadmin',
            name='describe',
            field=models.TextField(null=True, verbose_name='Коммент'),
        ),
        migrations.AlterModelTable(
            name='statusbyadmin',
            table='StatusByAdmin',
        ),
    ]
