# Generated by Django 5.1.1 on 2024-10-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_electiveprofilecourse_all_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electiveprofilecourse',
            name='someCourses',
        ),
        migrations.AddField(
            model_name='electiveprofile',
            name='someCourses',
            field=models.TextField(null=True, verbose_name='ЧТО ЭТО)'),
        ),
    ]
